apiVersion: v1
kind: Service
metadata:
  name: viking-svc-lb
  labels:
    app: viking-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: viking-nginx
